version: '3.4'

services:
  lymrhospitalrami:
    image: lymrhospitalrami
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3050:3050
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "getPatientReports.js"]
